name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.APP_DIR }}
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          printf '%s' "$ENV_FILE" > .env



      - name: Build project
        run: npm run build

      - name: Package artifacts
        run: |
          tar -czf release.tar.gz dist package.json package-lock.json ecosystem.config.js .env

      - name: Upload artifacts to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "release.tar.gz"
          target: "${{ secrets.APP_DIR }}"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.APP_DIR }}
            tar -xzf release.tar.gz
            rm release.tar.gz
            npm ci --omit=dev
            pm2 start ecosystem.config.js --only ${{ secrets.PM2_PROCESS }} --update-env || pm2 start ecosystem.config.js
            pm2 save
